config/routes.rb
Rails.application.routes.draw do

  root to: 'salads#index'

  resources :salads do
    resources :quantities, only: [:create]
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :quantities, dependent: :destroy
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :salad
end

app/models/salad.rb
class Salad < ActiveRecord::Base
  has_many :quantities, dependent: :destroy
  has_many :ingredients, through: :quantities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  before_action :set_quantity, only: [:show, :edit, :update, :destroy]
  before_action :load_ingredients, only: [:edit, :new]
  before_action :load_salad, only: [:edit, :new, :create, :destroy]
  def index
    @quantities = Quantity.all
  end

  def show
  end

  def new
    @quantity = Quantity.new
    @quantity.salad_id = @salad.id
  end

  def create
    @quantity = Quantity.new(quantity_params)
    @quantity.save
    redirect_to salad_path(@salad)
  end

  def edit
  end

  def update
    @quantity.update(quantity_params)
    redirect_to salad_path(@salad)
  end

  def destroy
    @quantity.destroy
    redirect_to salad_path(@salad)
  end

  private

  def quantity_params
    params.require(:quantity).permit(:name)
  end

  def set_quantity
    @quantity = Quantity.find(params[:id])
  end

  def load_ingredients
    @ingredients = Ingredient.all
  end

  def load_salad
    @salad = Salad.find(params[:salad_id])
  end
end

app/controllers/salads_controller.rb
class SaladsController < ApplicationController
  before_action :set_salad, only: [:show, :edit, :update, :destroy]
  def index
    @salads = Salad.all
  end

  def show
    @quantity = Quantity.new
  end

  def new
    @salad = Salad.new
  end

  def create
    @salad = Salad.new(salad_params)
    @salad.save
    redirect_to salad_path(@salad)
  end

  def edit
  end

  def update
    @salad.update(salad_params)
    redirect_to salad_path(@salad)
  end

  def destroy
    @salad.destroy
    redirect_to salads_path
  end

  private

  def salad_params
    params.require(:salad).permit(:name)
  end

  def set_salad
    @salad = Salad.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/salads_helper.rb
module SaladsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>
<body>

<%= yield %>

</body>
</html>

app/views/quantities/_form.html.erb
<%= simple_form_for([@salad, @quantity]) do |f| %>
    <%= f.input :ingredient, collection: @ingredients %>
    <%= f.input :description, placeholder: "Description" %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/quantities/create.html.erb
<h1>Quantities#create</h1>
<p>Find me in app/views/quantities/create.html.erb</p>

app/views/quantities/destroy.html.erb
<h1>Quantities#destroy</h1>
<p>Find me in app/views/quantities/destroy.html.erb</p>

app/views/quantities/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Modifier la quantité</h1>
      <%= render 'form' %>
      <%= link_to "Revenir à l'accueil", quantities_path %>
    </div>
  </div>
</div>

app/views/quantities/index.html.erb
<h1>Quantities#index</h1>
<p>Find me in app/views/quantities/index.html.erb</p>

app/views/quantities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Nouvelle quantité</h1>
      <%= render 'form' %>
      <%= link_to "Revenir à l'accueil", salads_path %>
    </div>
  </div>
</div>

app/views/quantities/show.html.erb
<h1>Quantities#show</h1>
<p>Find me in app/views/quantities/show.html.erb</p>

app/views/quantities/update.html.erb
<h1>Quantities#update</h1>
<p>Find me in app/views/quantities/update.html.erb</p>

app/views/salads/_form.html.erb
<%= simple_form_for(@salad) do |f| %>
    <%= f.input :name, placeholder: "Salade" %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/salads/create.html.erb
<h1>Salads#create</h1>
<p>Find me in app/views/salads/create.html.erb</p>

app/views/salads/destroy.html.erb
<h1>Salads#destroy</h1>
<p>Find me in app/views/salads/destroy.html.erb</p>

app/views/salads/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Modifier la salade</h1>
      <%= render 'form' %>
      <%= link_to "Revenir à l'accueil", salads_path %>
    </div>
  </div>
</div>

app/views/salads/index.html.erb
<h1>Générateur de salades</h1>
<div class="text-center padded">
  <%= link_to "Créer une salade", new_salad_path, class: "btn btn-primary" %>
</div>

<div class="container">
  <div class="row">
    <% @salads.each do |salad| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card text-center">
          <div class="card-body">
            <%= link_to salad.name, salad_path(salad) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/salads/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Nouvelle salade</h1>
      <%= render 'form' %>
      <%= link_to "Revenir à l'accueil", salads_path %>
    </div>
  </div>
</div>

app/views/salads/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @salad.name %></h1>
      <ul class="list-unstyled">
        <% @salad.quantities.each do |quantity| %>
          <li><%= link_to quantity.ingredient.name, ingredient_path(quantity.ingredient) %> : <%= quantity.description %> <%= link_to "<i class='fa fa-close'></i>".html_safe, quantity_path(quantity), method: :delete, data: { confirm: "Êtes-vous sûr ?" } %></li>
        <% end %>
      </ul>
      <br>

      <%= simple_form_for([@salad, @quantity]) do |f| %>
        <%= f.input :description %>
        <%= f.input :ingredient_id, collection: @ingredients %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>

      <p><%= link_to "Retour à l'accueil", salads_path %></p>
    </div>
  </div>
</div>

app/views/salads/update.html.erb
<h1>Salads#update</h1>
<p>Find me in app/views/salads/update.html.erb</p>